### ISSUE TITLE
RHEOS exits silently during startup

### ISSUE THREAD

**Issue by mgmart** [LINVALE/RHEOS#2]
I'm using RHEOS on a Raspberry Pi and installed it by `git clone`,` npm install` and run it with `node .`

After detecting my soundbar RHEOS exits silently.

```
xxxx@home-bridge:~/install/RHEOS $ node .
192.168.x.147,Linux,home-bridge,linux,arm
┌─────────┬──────────────┬────────────┬───────────────────┬─────────────────┬────────────┐
│ (index) │     name     │    pid     │       model       │       ip        │ resolution │
├─────────┼──────────────┼────────────┼───────────────────┼─────────────────┼────────────┤
│    0    │ 'Wohnzimmer' │ 1942336755 │ 'Denon DHT-S516H' │ '192.168.x.110' │    'CD'    │
└─────────┴──────────────┴────────────┴───────────────────┴─────────────────┴────────────┘
xxxx@home-bridge:~/install/RHEOS $
```

**Comment by LINVALE** [comment]
Thanks.

Please check that you have execute permissions set for all files   ~/install/RHEOS/UPnP/Bin

If you sudo chmod  +x ~/install/UPnP/Bin/*

I've had some problems with the permissions on set up and will check the repository but this may be the problem.

Otherwise please share the log file located on /RHEOS/UPnP/Profiles/Wohnzimmer.log and I l will see if I can track down the issue..

**Comment by mgmart** [comment]
After setting the execute permissions in UPnP/Bin it works like a charm.
Thank you!
